version: '3.9'

services:
  frontend:
    build:
      context: ../../../frontend # <--- Path to your cloned frontend repo relative to this frontend.yml
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
    environment:
      NODE_RPC_URL: http://host.docker.internal:63893